### ISSUE TITLE
Ctrl+` hotkey is broken

### ISSUE THREAD

**Issue by Keith94** [CodeFusion/StayOnTop#11]
Doesn't do anything in Firefox Nightly.

**Comment by Noitidart** [comment]
I'm guessing that we need to use a framescript to inject the hotkey into content processes.

**Comment by Noitidart** [comment]
@Keith94 oops I thought you were the developer of this addon haha I wasn't paying attention.

For now you can use Topick - https://addons.mozilla.org/en-US/firefox/addon/topick/ - if you are on Windows. I have an udpate coming out for it so it works on Mac and Linux as well. Topick is a bit different though, in that it works on all windows, not just Firefox windows.

**Comment by Noitidart** [comment]
Just updated Topick - its more robust now and allows changing the hotkey - https://addons.mozilla.org/en-US/firefox/addon/topick/
