### ISSUE TITLE
The pin icon is not accurate when multiple windows

### ISSUE THREAD

**Issue by Noitidart** [CodeFusion/StayOnTop#9]
When we have multiple windows with the pin icon toolbar button. It is showing "down" when it is not pinned. Because it is using a global `buttonActive` variable. This button should be based on the window state.

**Comment by CodeFusion** [comment]
I can't seem to replicate this. Did you fix it in #6?

**Comment by Noitidart** [comment]
Thanks brother for looking into this. I actually didn't try this. Just by looking at the code though, it seems to use a global and it seems it can have an issue. If there is no issue then excuse this please. :)

**Comment by CodeFusion** [comment]
I've tested a number of different scenarios and it doesn't seem to be an issue - I believe each window has its own copy of that variable, and it is only at window scope, rather than program.

I am closing this for now, reopen it or create another issue if you find that it is actually a bug
